sudo: required
dist: trusty
env:
  global:
  # DOCKER_USER
  - secure: "VGpnJmdN4tt4mu4o6TbM239hPid1DktCrDj+Gt5yNWxY4zHNdxQj9BOTe4Hi0rP2KymMGHjxxHvZnqx+G8MwfFfO57nMUXz63sjgCLHR778UiCivLxeyNz153LlGJsXCLwXIJ3ch7wKMiNcM56KswujQnIVr92cGm0Pkw/jMrPgrX8L7i7xIsuM9Oos0tIyV0OCGhSdoayoG7mHPU1kFz0M2eVvDeai1PYPEOAcDg2pQlkpcEGPwdtl+hOCGnOxwyqCXc6kYvv2ZpEt7TGI726GgkPp9E+1w9riQ0ktED6in6eO/a0ywhlOx5siRhn45SC+GZP5PwZhZbvOZLz0/Kah8NPCcz6XmcZpko5StMbPcHG6GndJuz3TW8ckpOny3bzkklVlbOmst1gWT14Wldnd+J4iXW80SnHcvf5cy+eLES4cn73roGuUpfzGQzSSPScLfozr+7AK5x3M2vrtKJZ9EJTo8SbsKmVrlyrsHvI3WH7DNNR0ew54uEgiYFY20z8FB3n9FHv1meNxIylrHyVSc8CzEPwYAYl0lnBXEFJnUZ8R9/IcHS9Xp+x0C7ub6m2iTnDDvfF4O8XfwgG/aVPFGnz0dmjGoAXyXsSoF26ci+rt6QhgxrQB2OLJxVvpyswQEHtOlUrAEdNSUezLpDnrHS3En8N08/Ak6mJ3lG8k="
  # DOCKER_PASS
  - secure: "OBDWtm4AekCXVLPMSwN6xYv7J0MO5rtWbU5KfCxv0aZazE2XNgg6SuEt7L3pZxI0VOPRsbgOnxg7ZD+Xce6QsdkuTqUC8GwWIvQFqLPC2Uqzv1Zym1mu/ZBjAr3yLWcifWTCnCBjI7lSbg+aoHYloYGWZbh60CXlEtTEy0E+foe6afAovWzAwQ8eSEJbOMLNS2kqQ0R96qWvVdmXOVJ7i6qFXtHFmrCma129FUG9LcWkiPYaKYfXBrOpwiq+JMP8Sz+4k1XJI1AQN8nbPQqJFgrVCsJcf1Bo6c1Bt2/GWiiDl7UyPszPEyNc7IRxjHTMuzMDG9aYvWw5+Ay3Ait0ljGFMAwAcJTcnBsIRZ9zAo16xik8dGPbDBBJwgfl3tIiJ8jy/Wq3bdZr9I0+14IlbGXa/k3foIu+EoesJAo5ia/hK7lNOaS9YrgEq0bbzV4DjsFAzAs1KC+DvfkgNWNY9a7X22BuEmboNyNuqmNZssps3CpHvCyXS3y1KBELAxSeEqT/mJsRp5Rl/9I6augc6H+Ca99ZmgHSeju+kcFMIDa1KZQXKAn1ejn5NqaOAbs6RmLVJIuNL6o7gqmobzsd+2whKfV+WzRos1a2pfIYo6bnAvSe6QOlqRxzUtpQpKLQCona6XOQnUpBV5/eTl2rCe3r0VuC/jraaCrMYbU+Qj4="
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_c06c602c11d3_key -iv $encrypted_c06c602c11d3_iv -in docker-creds.tar.enc -out docker-creds.tar -d

stages:
- name: build
- name: deploy
jobs:
  include:
  - stage: build
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build --pull --rm -t threethink/shit-city-web:${TRAVIS_COMMIT} .
    - docker push threethink/shit-city-web:${TRAVIS_COMMIT}
    if: branch = master
  - stage: deploy
    env:
      # DOCKER_HOST
    - secure: "wSwxOpMsYbLkhGoZaPYN85G0NXrNRR6ob4fTrmw1BOQzoL/pNPCxw+m4qw5s8nUCRBEamObNunKht9HZrF7Ia0Dop+FRahAaD1VW7rHijExNqewG047nbKYTfBYf5JJ/ylXMrkDKNEIFEihmVh4CczCBmrWT50h7UfM2rO3DGzJNnqvfo3Lry1a7SOuElmOqlymRxuIvfXieDacoXW9GdBhPC5xwlNR0cDI7COmoVPHnhHD/KxuzWumfM4CmXIhwfOVlEaDfb+U6atv6oJehuJpbqJ/33GMt6z16FgHncAZE7SDzHQA/QgoNJriSE9uOT3SO7B+LhacuZKMXDvil7KT033QoogMwyYGDwIk/m2dUbJg0VpqzP++YsM8QaMbMak1xfnJN5aQ6liQGphhJtW7GQ3/1aAzxEB0zZVufnKnr3gjAR2tECzbEcj0veLR803GFccZBaC2JK7EV7F9zF60lyQ5ujOqvSqEMHbctLnaibwjJqCMZ3bZ15mG5tqml4vJ4VyFgDkUh8hVwIv4PT3pOxxY/bRFEiKtJKHoj6x0WCbJ1QwCguzcdKwCKO2bx6+DSoMxg2eRAKSvr3+XJQKz5O2dHrjTMOKmXoTf+VlydWSi9TFgB2u+xw/ybmBFyJ0Tl2sTfQWMlyKpZgbKISx0b/QQ9t2fJHP3BkuDsdto="
    - DOCKER_CERT_PATH="./docker-creds"
    - DOCKER_TLS_VERIFY="True"
    script:
      - tar xvf docker-creds.tar
      - docker-compose up -d
    if: branch = master
